/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MagicLinkRouteImport } from './routes/magic-link'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/app'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as MktRouteImport } from './routes/_mkt'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as MktIndexRouteImport } from './routes/_mkt.index'
import { Route as AppOrganizationIdRouteImport } from './routes/app.$organizationId'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminSubscriptionsRouteImport } from './routes/admin.subscriptions'
import { Route as AdminSessionsRouteImport } from './routes/admin.sessions'
import { Route as AdminCustomersRouteImport } from './routes/admin.customers'
import { Route as MktPricingRouteImport } from './routes/_mkt.pricing'
import { Route as AppOrganizationIdIndexRouteImport } from './routes/app.$organizationId.index'
import { Route as AppOrganizationIdWorkflowRouteImport } from './routes/app.$organizationId.workflow'
import { Route as AppOrganizationIdUploadRouteImport } from './routes/app.$organizationId.upload'
import { Route as AppOrganizationIdMembersRouteImport } from './routes/app.$organizationId.members'
import { Route as AppOrganizationIdInvitationsRouteImport } from './routes/app.$organizationId.invitations'
import { Route as AppOrganizationIdInspectorRouteImport } from './routes/app.$organizationId.inspector'
import { Route as AppOrganizationIdGoogleRouteImport } from './routes/app.$organizationId.google'
import { Route as AppOrganizationIdChatRouteImport } from './routes/app.$organizationId.chat'
import { Route as AppOrganizationIdBillingRouteImport } from './routes/app.$organizationId.billing'
import { Route as AppOrganizationIdAgentRouteImport } from './routes/app.$organizationId.agent'
import { Route as ApiGoogleCallbackRouteImport } from './routes/api/google/callback'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiOrgOrganizationIdUploadImageNameRouteImport } from './routes/api/org.$organizationId.upload-image.$name'
import { Route as ApiE2eDeleteUserEmailRouteImport } from './routes/api/e2e/delete/user/$email'

const MagicLinkRoute = MagicLinkRouteImport.update({
  id: '/magic-link',
  path: '/magic-link',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const MktRoute = MktRouteImport.update({
  id: '/_mkt',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const MktIndexRoute = MktIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MktRoute,
} as any)
const AppOrganizationIdRoute = AppOrganizationIdRouteImport.update({
  id: '/$organizationId',
  path: '/$organizationId',
  getParentRoute: () => AppRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSubscriptionsRoute = AdminSubscriptionsRouteImport.update({
  id: '/subscriptions',
  path: '/subscriptions',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSessionsRoute = AdminSessionsRouteImport.update({
  id: '/sessions',
  path: '/sessions',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCustomersRoute = AdminCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AdminRoute,
} as any)
const MktPricingRoute = MktPricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => MktRoute,
} as any)
const AppOrganizationIdIndexRoute = AppOrganizationIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppOrganizationIdRoute,
} as any)
const AppOrganizationIdWorkflowRoute =
  AppOrganizationIdWorkflowRouteImport.update({
    id: '/workflow',
    path: '/workflow',
    getParentRoute: () => AppOrganizationIdRoute,
  } as any)
const AppOrganizationIdUploadRoute = AppOrganizationIdUploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => AppOrganizationIdRoute,
} as any)
const AppOrganizationIdMembersRoute =
  AppOrganizationIdMembersRouteImport.update({
    id: '/members',
    path: '/members',
    getParentRoute: () => AppOrganizationIdRoute,
  } as any)
const AppOrganizationIdInvitationsRoute =
  AppOrganizationIdInvitationsRouteImport.update({
    id: '/invitations',
    path: '/invitations',
    getParentRoute: () => AppOrganizationIdRoute,
  } as any)
const AppOrganizationIdInspectorRoute =
  AppOrganizationIdInspectorRouteImport.update({
    id: '/inspector',
    path: '/inspector',
    getParentRoute: () => AppOrganizationIdRoute,
  } as any)
const AppOrganizationIdGoogleRoute = AppOrganizationIdGoogleRouteImport.update({
  id: '/google',
  path: '/google',
  getParentRoute: () => AppOrganizationIdRoute,
} as any)
const AppOrganizationIdChatRoute = AppOrganizationIdChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AppOrganizationIdRoute,
} as any)
const AppOrganizationIdBillingRoute =
  AppOrganizationIdBillingRouteImport.update({
    id: '/billing',
    path: '/billing',
    getParentRoute: () => AppOrganizationIdRoute,
  } as any)
const AppOrganizationIdAgentRoute = AppOrganizationIdAgentRouteImport.update({
  id: '/agent',
  path: '/agent',
  getParentRoute: () => AppOrganizationIdRoute,
} as any)
const ApiGoogleCallbackRoute = ApiGoogleCallbackRouteImport.update({
  id: '/api/google/callback',
  path: '/api/google/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOrgOrganizationIdUploadImageNameRoute =
  ApiOrgOrganizationIdUploadImageNameRouteImport.update({
    id: '/api/org/$organizationId/upload-image/$name',
    path: '/api/org/$organizationId/upload-image/$name',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiE2eDeleteUserEmailRoute = ApiE2eDeleteUserEmailRouteImport.update({
  id: '/api/e2e/delete/user/$email',
  path: '/api/e2e/delete/user/$email',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof MktIndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/magic-link': typeof MagicLinkRoute
  '/pricing': typeof MktPricingRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/sessions': typeof AdminSessionsRoute
  '/admin/subscriptions': typeof AdminSubscriptionsRoute
  '/admin/users': typeof AdminUsersRoute
  '/app/$organizationId': typeof AppOrganizationIdRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/app/': typeof AppIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/google/callback': typeof ApiGoogleCallbackRoute
  '/app/$organizationId/agent': typeof AppOrganizationIdAgentRoute
  '/app/$organizationId/billing': typeof AppOrganizationIdBillingRoute
  '/app/$organizationId/chat': typeof AppOrganizationIdChatRoute
  '/app/$organizationId/google': typeof AppOrganizationIdGoogleRoute
  '/app/$organizationId/inspector': typeof AppOrganizationIdInspectorRoute
  '/app/$organizationId/invitations': typeof AppOrganizationIdInvitationsRoute
  '/app/$organizationId/members': typeof AppOrganizationIdMembersRoute
  '/app/$organizationId/upload': typeof AppOrganizationIdUploadRoute
  '/app/$organizationId/workflow': typeof AppOrganizationIdWorkflowRoute
  '/app/$organizationId/': typeof AppOrganizationIdIndexRoute
  '/api/e2e/delete/user/$email': typeof ApiE2eDeleteUserEmailRoute
  '/api/org/$organizationId/upload-image/$name': typeof ApiOrgOrganizationIdUploadImageNameRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/magic-link': typeof MagicLinkRoute
  '/pricing': typeof MktPricingRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/sessions': typeof AdminSessionsRoute
  '/admin/subscriptions': typeof AdminSubscriptionsRoute
  '/admin/users': typeof AdminUsersRoute
  '/': typeof MktIndexRoute
  '/admin': typeof AdminIndexRoute
  '/app': typeof AppIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/google/callback': typeof ApiGoogleCallbackRoute
  '/app/$organizationId/agent': typeof AppOrganizationIdAgentRoute
  '/app/$organizationId/billing': typeof AppOrganizationIdBillingRoute
  '/app/$organizationId/chat': typeof AppOrganizationIdChatRoute
  '/app/$organizationId/google': typeof AppOrganizationIdGoogleRoute
  '/app/$organizationId/inspector': typeof AppOrganizationIdInspectorRoute
  '/app/$organizationId/invitations': typeof AppOrganizationIdInvitationsRoute
  '/app/$organizationId/members': typeof AppOrganizationIdMembersRoute
  '/app/$organizationId/upload': typeof AppOrganizationIdUploadRoute
  '/app/$organizationId/workflow': typeof AppOrganizationIdWorkflowRoute
  '/app/$organizationId': typeof AppOrganizationIdIndexRoute
  '/api/e2e/delete/user/$email': typeof ApiE2eDeleteUserEmailRoute
  '/api/org/$organizationId/upload-image/$name': typeof ApiOrgOrganizationIdUploadImageNameRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_mkt': typeof MktRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/magic-link': typeof MagicLinkRoute
  '/_mkt/pricing': typeof MktPricingRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/sessions': typeof AdminSessionsRoute
  '/admin/subscriptions': typeof AdminSubscriptionsRoute
  '/admin/users': typeof AdminUsersRoute
  '/app/$organizationId': typeof AppOrganizationIdRouteWithChildren
  '/_mkt/': typeof MktIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/app/': typeof AppIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/google/callback': typeof ApiGoogleCallbackRoute
  '/app/$organizationId/agent': typeof AppOrganizationIdAgentRoute
  '/app/$organizationId/billing': typeof AppOrganizationIdBillingRoute
  '/app/$organizationId/chat': typeof AppOrganizationIdChatRoute
  '/app/$organizationId/google': typeof AppOrganizationIdGoogleRoute
  '/app/$organizationId/inspector': typeof AppOrganizationIdInspectorRoute
  '/app/$organizationId/invitations': typeof AppOrganizationIdInvitationsRoute
  '/app/$organizationId/members': typeof AppOrganizationIdMembersRoute
  '/app/$organizationId/upload': typeof AppOrganizationIdUploadRoute
  '/app/$organizationId/workflow': typeof AppOrganizationIdWorkflowRoute
  '/app/$organizationId/': typeof AppOrganizationIdIndexRoute
  '/api/e2e/delete/user/$email': typeof ApiE2eDeleteUserEmailRoute
  '/api/org/$organizationId/upload-image/$name': typeof ApiOrgOrganizationIdUploadImageNameRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/app'
    | '/login'
    | '/magic-link'
    | '/pricing'
    | '/admin/customers'
    | '/admin/sessions'
    | '/admin/subscriptions'
    | '/admin/users'
    | '/app/$organizationId'
    | '/admin/'
    | '/app/'
    | '/api/auth/$'
    | '/api/google/callback'
    | '/app/$organizationId/agent'
    | '/app/$organizationId/billing'
    | '/app/$organizationId/chat'
    | '/app/$organizationId/google'
    | '/app/$organizationId/inspector'
    | '/app/$organizationId/invitations'
    | '/app/$organizationId/members'
    | '/app/$organizationId/upload'
    | '/app/$organizationId/workflow'
    | '/app/$organizationId/'
    | '/api/e2e/delete/user/$email'
    | '/api/org/$organizationId/upload-image/$name'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/magic-link'
    | '/pricing'
    | '/admin/customers'
    | '/admin/sessions'
    | '/admin/subscriptions'
    | '/admin/users'
    | '/'
    | '/admin'
    | '/app'
    | '/api/auth/$'
    | '/api/google/callback'
    | '/app/$organizationId/agent'
    | '/app/$organizationId/billing'
    | '/app/$organizationId/chat'
    | '/app/$organizationId/google'
    | '/app/$organizationId/inspector'
    | '/app/$organizationId/invitations'
    | '/app/$organizationId/members'
    | '/app/$organizationId/upload'
    | '/app/$organizationId/workflow'
    | '/app/$organizationId'
    | '/api/e2e/delete/user/$email'
    | '/api/org/$organizationId/upload-image/$name'
  id:
    | '__root__'
    | '/_mkt'
    | '/admin'
    | '/app'
    | '/login'
    | '/magic-link'
    | '/_mkt/pricing'
    | '/admin/customers'
    | '/admin/sessions'
    | '/admin/subscriptions'
    | '/admin/users'
    | '/app/$organizationId'
    | '/_mkt/'
    | '/admin/'
    | '/app/'
    | '/api/auth/$'
    | '/api/google/callback'
    | '/app/$organizationId/agent'
    | '/app/$organizationId/billing'
    | '/app/$organizationId/chat'
    | '/app/$organizationId/google'
    | '/app/$organizationId/inspector'
    | '/app/$organizationId/invitations'
    | '/app/$organizationId/members'
    | '/app/$organizationId/upload'
    | '/app/$organizationId/workflow'
    | '/app/$organizationId/'
    | '/api/e2e/delete/user/$email'
    | '/api/org/$organizationId/upload-image/$name'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  MktRoute: typeof MktRouteWithChildren
  AdminRoute: typeof AdminRouteWithChildren
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  MagicLinkRoute: typeof MagicLinkRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiGoogleCallbackRoute: typeof ApiGoogleCallbackRoute
  ApiE2eDeleteUserEmailRoute: typeof ApiE2eDeleteUserEmailRoute
  ApiOrgOrganizationIdUploadImageNameRoute: typeof ApiOrgOrganizationIdUploadImageNameRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/magic-link': {
      id: '/magic-link'
      path: '/magic-link'
      fullPath: '/magic-link'
      preLoaderRoute: typeof MagicLinkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_mkt': {
      id: '/_mkt'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof MktRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_mkt/': {
      id: '/_mkt/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof MktIndexRouteImport
      parentRoute: typeof MktRoute
    }
    '/app/$organizationId': {
      id: '/app/$organizationId'
      path: '/$organizationId'
      fullPath: '/app/$organizationId'
      preLoaderRoute: typeof AppOrganizationIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/subscriptions': {
      id: '/admin/subscriptions'
      path: '/subscriptions'
      fullPath: '/admin/subscriptions'
      preLoaderRoute: typeof AdminSubscriptionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/sessions': {
      id: '/admin/sessions'
      path: '/sessions'
      fullPath: '/admin/sessions'
      preLoaderRoute: typeof AdminSessionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/customers': {
      id: '/admin/customers'
      path: '/customers'
      fullPath: '/admin/customers'
      preLoaderRoute: typeof AdminCustomersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_mkt/pricing': {
      id: '/_mkt/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof MktPricingRouteImport
      parentRoute: typeof MktRoute
    }
    '/app/$organizationId/': {
      id: '/app/$organizationId/'
      path: '/'
      fullPath: '/app/$organizationId/'
      preLoaderRoute: typeof AppOrganizationIdIndexRouteImport
      parentRoute: typeof AppOrganizationIdRoute
    }
    '/app/$organizationId/workflow': {
      id: '/app/$organizationId/workflow'
      path: '/workflow'
      fullPath: '/app/$organizationId/workflow'
      preLoaderRoute: typeof AppOrganizationIdWorkflowRouteImport
      parentRoute: typeof AppOrganizationIdRoute
    }
    '/app/$organizationId/upload': {
      id: '/app/$organizationId/upload'
      path: '/upload'
      fullPath: '/app/$organizationId/upload'
      preLoaderRoute: typeof AppOrganizationIdUploadRouteImport
      parentRoute: typeof AppOrganizationIdRoute
    }
    '/app/$organizationId/members': {
      id: '/app/$organizationId/members'
      path: '/members'
      fullPath: '/app/$organizationId/members'
      preLoaderRoute: typeof AppOrganizationIdMembersRouteImport
      parentRoute: typeof AppOrganizationIdRoute
    }
    '/app/$organizationId/invitations': {
      id: '/app/$organizationId/invitations'
      path: '/invitations'
      fullPath: '/app/$organizationId/invitations'
      preLoaderRoute: typeof AppOrganizationIdInvitationsRouteImport
      parentRoute: typeof AppOrganizationIdRoute
    }
    '/app/$organizationId/inspector': {
      id: '/app/$organizationId/inspector'
      path: '/inspector'
      fullPath: '/app/$organizationId/inspector'
      preLoaderRoute: typeof AppOrganizationIdInspectorRouteImport
      parentRoute: typeof AppOrganizationIdRoute
    }
    '/app/$organizationId/google': {
      id: '/app/$organizationId/google'
      path: '/google'
      fullPath: '/app/$organizationId/google'
      preLoaderRoute: typeof AppOrganizationIdGoogleRouteImport
      parentRoute: typeof AppOrganizationIdRoute
    }
    '/app/$organizationId/chat': {
      id: '/app/$organizationId/chat'
      path: '/chat'
      fullPath: '/app/$organizationId/chat'
      preLoaderRoute: typeof AppOrganizationIdChatRouteImport
      parentRoute: typeof AppOrganizationIdRoute
    }
    '/app/$organizationId/billing': {
      id: '/app/$organizationId/billing'
      path: '/billing'
      fullPath: '/app/$organizationId/billing'
      preLoaderRoute: typeof AppOrganizationIdBillingRouteImport
      parentRoute: typeof AppOrganizationIdRoute
    }
    '/app/$organizationId/agent': {
      id: '/app/$organizationId/agent'
      path: '/agent'
      fullPath: '/app/$organizationId/agent'
      preLoaderRoute: typeof AppOrganizationIdAgentRouteImport
      parentRoute: typeof AppOrganizationIdRoute
    }
    '/api/google/callback': {
      id: '/api/google/callback'
      path: '/api/google/callback'
      fullPath: '/api/google/callback'
      preLoaderRoute: typeof ApiGoogleCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/org/$organizationId/upload-image/$name': {
      id: '/api/org/$organizationId/upload-image/$name'
      path: '/api/org/$organizationId/upload-image/$name'
      fullPath: '/api/org/$organizationId/upload-image/$name'
      preLoaderRoute: typeof ApiOrgOrganizationIdUploadImageNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/e2e/delete/user/$email': {
      id: '/api/e2e/delete/user/$email'
      path: '/api/e2e/delete/user/$email'
      fullPath: '/api/e2e/delete/user/$email'
      preLoaderRoute: typeof ApiE2eDeleteUserEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface MktRouteChildren {
  MktPricingRoute: typeof MktPricingRoute
  MktIndexRoute: typeof MktIndexRoute
}

const MktRouteChildren: MktRouteChildren = {
  MktPricingRoute: MktPricingRoute,
  MktIndexRoute: MktIndexRoute,
}

const MktRouteWithChildren = MktRoute._addFileChildren(MktRouteChildren)

interface AdminRouteChildren {
  AdminCustomersRoute: typeof AdminCustomersRoute
  AdminSessionsRoute: typeof AdminSessionsRoute
  AdminSubscriptionsRoute: typeof AdminSubscriptionsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminCustomersRoute: AdminCustomersRoute,
  AdminSessionsRoute: AdminSessionsRoute,
  AdminSubscriptionsRoute: AdminSubscriptionsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AppOrganizationIdRouteChildren {
  AppOrganizationIdAgentRoute: typeof AppOrganizationIdAgentRoute
  AppOrganizationIdBillingRoute: typeof AppOrganizationIdBillingRoute
  AppOrganizationIdChatRoute: typeof AppOrganizationIdChatRoute
  AppOrganizationIdGoogleRoute: typeof AppOrganizationIdGoogleRoute
  AppOrganizationIdInspectorRoute: typeof AppOrganizationIdInspectorRoute
  AppOrganizationIdInvitationsRoute: typeof AppOrganizationIdInvitationsRoute
  AppOrganizationIdMembersRoute: typeof AppOrganizationIdMembersRoute
  AppOrganizationIdUploadRoute: typeof AppOrganizationIdUploadRoute
  AppOrganizationIdWorkflowRoute: typeof AppOrganizationIdWorkflowRoute
  AppOrganizationIdIndexRoute: typeof AppOrganizationIdIndexRoute
}

const AppOrganizationIdRouteChildren: AppOrganizationIdRouteChildren = {
  AppOrganizationIdAgentRoute: AppOrganizationIdAgentRoute,
  AppOrganizationIdBillingRoute: AppOrganizationIdBillingRoute,
  AppOrganizationIdChatRoute: AppOrganizationIdChatRoute,
  AppOrganizationIdGoogleRoute: AppOrganizationIdGoogleRoute,
  AppOrganizationIdInspectorRoute: AppOrganizationIdInspectorRoute,
  AppOrganizationIdInvitationsRoute: AppOrganizationIdInvitationsRoute,
  AppOrganizationIdMembersRoute: AppOrganizationIdMembersRoute,
  AppOrganizationIdUploadRoute: AppOrganizationIdUploadRoute,
  AppOrganizationIdWorkflowRoute: AppOrganizationIdWorkflowRoute,
  AppOrganizationIdIndexRoute: AppOrganizationIdIndexRoute,
}

const AppOrganizationIdRouteWithChildren =
  AppOrganizationIdRoute._addFileChildren(AppOrganizationIdRouteChildren)

interface AppRouteChildren {
  AppOrganizationIdRoute: typeof AppOrganizationIdRouteWithChildren
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppOrganizationIdRoute: AppOrganizationIdRouteWithChildren,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  MktRoute: MktRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  MagicLinkRoute: MagicLinkRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiGoogleCallbackRoute: ApiGoogleCallbackRoute,
  ApiE2eDeleteUserEmailRoute: ApiE2eDeleteUserEmailRoute,
  ApiOrgOrganizationIdUploadImageNameRoute:
    ApiOrgOrganizationIdUploadImageNameRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
